// The NAV-CONTEXT built-ins (`${__nav.*}` / `${__page.*}`) — nav-context-vars scope, Slice 1. PURE: a
// resolved nav chain in, a flat `Builtins` map out. No React, no `@/` shell imports (this module ships
// inside the federation-shared `vars` singleton, like the rest of `lib/vars`).
//
// WHY A SEPARATE FILE. `resolveBuiltins` already owns time/identity/workspace; nav context is a
// different input class (the shell's resolved nav model, derived from the URL) with its own
// omitted-vs-empty rules. One responsibility per file (FILE-LAYOUT).
//
// OMITTED AND EMPTY ARE OPPOSITE RENDERS, AND THE CHOICE IS PER KEY. `interpolate` leaves an unknown
// name LITERAL, so an omitted key means the reference survives as text; an empty-string key erases the
// reference. A key is OMITTED when the context is genuinely unknown (no nav node addresses this URL;
// above the tree root) and EMPTY when it is known-absent — `${__page.ext}` on a hand-authored board
// must render nothing, because "generated by ${__page.ext}" would otherwise sit in that heading
// forever. That single exception is the one place the two rules differ, and it is deliberate.
//
// NEVER SUPPLIED BY A CELL OR AN IFRAME. The shell resolves this from its own nav model — the same
// un-spoofable posture as `identity`/`workspace`. An extension knows its own labels but not the host
// tree it was mounted into, so letting it CLAIM a parent chain would make `${__nav.*}` as forgeable as
// a client-supplied `${__user.login}`.

import type { Builtins } from "./types";

/** The nav chain the current URL ADDRESSES — derived by the shell from its resolved nav model, never
 *  from click state (so refresh, bookmark, deep link and shared link all resolve identically). */
export interface NavContext {
  /** Labels root-first, ending with the item's OWN label. Empty ⇒ no nav context. */
  path: string[];
  /** The item's stable key/slug — survives a relabel or a translation. */
  id?: string;
  /** The item's pinned heading override (Slice 4 — needs the upstream `NavItem.title_template`). */
  titleTemplate?: string;
  /** Did this chain come from a row targeting a DASHBOARD (not a surface)? A board URL lights BOTH the
   *  ext child that names it and the stock "Dashboards" surface row, and the shell prefers the former
   *  when choosing which chain to publish (`nav-context.ts`). Carried on the chain only to make that
   *  choice; it renders nothing and produces no `__nav.*` key. */
  dashboardTargeted?: boolean;
}

/** The separator for `${__nav.path}`, matching the breadcrumb. Other separators are composed by hand
 *  from `${__nav.parent.label}` and friends. */
export const NAV_PATH_SEP = " / ";

/** The page-record inputs behind `${__page.*}`. */
export interface PageContext {
  /** The dashboard id — `${__page.id}`, an alias of the shipped `${__dashboard}`. */
  id?: string;
  /** The record's un-overridden `title` — `${__page.title}`. */
  title?: string;
  /** The `managedBy` extension id. `undefined` on a hand-authored board, which still yields an EMPTY
   *  `${__page.ext}` (see the header) as long as a page context exists at all. */
  ext?: string;
}

/** Flatten a nav chain + page record into the `__nav.*` / `__page.*` built-in keys.
 *
 *  A depth-1 path yields `__nav.label` and `__nav.path` only — the parent keys are OMITTED, so
 *  `${__nav.parent.label}` stays literal rather than rendering an empty gap in the middle of a heading.
 *  An empty/absent chain yields no `__nav.*` key at all. */
export function navBuiltins(nav?: NavContext, page?: PageContext): Builtins {
  const out: Builtins = {};

  const path = nav?.path?.filter((s) => s !== undefined && s !== null) ?? [];
  if (path.length > 0) {
    out["__nav.label"] = path[path.length - 1];
    if (path.length > 1) out["__nav.parent.label"] = path[path.length - 2];
    if (path.length > 2) out["__nav.parent.parent.label"] = path[path.length - 3];
    out["__nav.path"] = path.join(NAV_PATH_SEP);
    if (nav?.id !== undefined) out["__nav.id"] = nav.id;
  }

  if (page) {
    if (page.id !== undefined) out["__page.id"] = page.id;
    if (page.title !== undefined) out["__page.title"] = page.title;
    // The exception to the omission rule — see the header. A page context exists, so the provenance
    // question HAS an answer; on a hand-authored board that answer is "nothing".
    if (page.id !== undefined || page.title !== undefined) out["__page.ext"] = page.ext ?? "";
  }

  return out;
}
